name: Staging Deployment

on:
  push:
    branches:
      - release/**
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Staging Environment
        run: echo "Code deployed to Staging Environment"
